name: ingest
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - gdal
  - rasterio
  - numpy
  - pystac
  - rio-stac
  - fsspec
  - boto3
  - backoff
  - requests
  - jq
  - pip
  - pip:
    - maap-py
