name: ingest
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - gdal
  - rasterio
  - rioxarray
  - xarray
  - zarr>=3
  - numpy
  - pandas
  - dask
  - pystac
  - rio-stac
  - fsspec
  - s3fs
  - boto3
  - backoff
  - jq
  - pip
  - pip:
    - maap-py
    - earthaccess
