name: ingest
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - gdal
  - rasterio
  - rioxarray
  - xarray
  - numpy
  - scipy
  - pystac
  - rio-stac
  - fsspec
  - boto3
  - backoff
  - paramiko
  - jq
  - pip
  - pip:
    - maap-py==4.2.0
    - earthaccess
    - scp
    - asf-search
