name: ingest
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - gdal
  - rasterio
  - rioxarray
  - xarray
  - numpy
  - pystac
  - pystac-client
  - rio-stac
  - fsspec
  - boto3
  - aiohttp
  - backoff
  - jq
  - pip
  - pip:
    - maap-py
